name: build-web

run-name: ${{ github.actor }} is building web

on:
  pull_request:
    branches: ["main"]

defaults:
  run:
      working-directory: web

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-web:
    name: build-web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn
      - run: yarn build