name: learn-github-actions

run-name: ${{ github.actor }} is building and deploying web to GH Pages

on:
  push:
    branches: ["main"]

defaults:
  run:
      working-directory: web

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn
      - run: yarn build
  deploy-web:
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Structure of folder
        run: ls -R
      - run: yarn add netlify-cli -D
      - name: Deploy to Netlify
        env: 
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_API_KEY}}
        run: netlify deploy --dir=build
        
      
        
      